[package]
name = "mmoss-examples-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
mmoss = { path = "../mmoss"}
mmoss-proc-macros = { path = "../mmoss-proc-macros"}
anyhow.workspace = true
bincode.workspace = true
bevy = { workspace = true, features = ["std"]}
sdl2.workspace = true
